
[General]
learning_rate = 0.01
weight_decay = 0.0001
dropout = 0.2
seed = 0
hidden_dim = 64
max_epoch = 50
patience = 200
mini_batch_flag = False


[RGCN]
learning_rate = 0.01
weight_decay = 0.0001
dropout = 0.2

seed = 0
in_dim = 64
hidden_dim = 64
# number of weight matrix bases
n_bases = 40
num_layers = 3

max_epoch = 50
patience = 50
batch_size = 128
fanout = 4

validation = True
use_self_loop = False
mini_batch_flag = True
use_uva = True

[CompGCN]
learning_rate = 0.01
weight_decay = 0.0001
dropout = 0.2

seed = 0
num_layers = 2
in_dim = 32
hidden_dim = 32
out_dim = 32
;We restrict the number of hidden units to 32. from paper

max_epoch = 500
patience = 100
;sub(subtraction) mult(multiplication) ccorr(circular-correlation)
comp_fn = sub
validation = True
mini_batch_flag = True
batch_size = 128
fanout = 4
[HetGNN]
seed = 0
learning_rate = 0.001
weight_decay = 0.00001

dim = 128
max_epoch = 500
batch_size = 64
window_size = 5
num_workers = 4
batches_per_epoch = 50

rw_length = 50
rw_walks = 10
rwr_prob = 0.5

patience = 20
mini_batch_flag = True



[HAN]
seed = 0
learning_rate = 0.005
weight_decay = 0.001
dropout = 0.6

hidden_dim = 128
out_dim = 16
; number of attention heads
num_heads = 8
max_epoch = 200
patience = 100
mini_batch_flag = True


[NARS]
seed = 0
learning_rate = 0.003
weight_decay = 0.001
dropout = 0.7
hidden_dim = 64
out_dim = 16
num_heads = 8
num_hops = 2
max_epoch = 200
mini_batch_flag = False
R = 2
patience = 100
input_dropout = True
cpu_preprocess = True
ff_layer = 2

[MAGNN]
seed = 0
learning_rate = 0.005
weight_decay = 0.001
dropout = 0.3

hidden_dim = 64
out_dim = 3

inter_attn_feats = 128
;The number of attention heads
num_heads = 8
;The number of layers
num_layers = 4

;Maximum number of epoches
max_epoch = 10
patience = 30

;the type of encoder, e.g ['RotateE', 'Average', 'Linear']
encoder_type = RotateE
mini_batch_flag = False
batch_size = 8
num_samples = 5


[HGT]
seed = 0
learning_rate = 0.001
weight_decay = 0.0001
dropout = 0.4

batch_size = 5120
; batch_size = 2
patience = 40
hidden_dim = 64
; hidden_dim = 2
out_dim = 16
num_layers = 2
; num_layers = 1
num_heads = 8
; num_heads = 16
num_workers = 64
; num_workers = 128
max_epoch = 500
mini_batch_flag = True
fanout = 5
norm = True
use_uva = True




[general_HGNN]

gnn_type = gcnconv
dropout = 0.5
has_bn = true
activation = tanh
has_l2norm = true

hidden_dim = 64
max_epoch = 400
lr = 0.01

optimizer = Adam
weight_decay = 0.0001
patience = 40

layers_gnn = 4
layers_post_mp = 1
layers_pre_mp = 1
stage_type = stack

macro_func = attention
num_heads = 8
feat = 0
subgraph_extraction = metapath
mini_batch_flag = false

[homo_GNN]

gnn_type = gcnconv
dropout = 0.5
has_bn = true
activation = tanh
has_l2norm = true

hidden_dim = 64
max_epoch = 400
lr = 0.01

optimizer = Adam
weight_decay = 0.0001
patience = 40

layers_gnn = 4
layers_post_mp = 1
layers_pre_mp = 1
stage_type = stack

num_heads = 8
feat = 0
subgraph = metapath
mini_batch_flag = false



[SimpleHGN]
hidden_dim = 256
num_layers = 3
num_heads = 8
feats_drop_rate = 0.2
slope = 0.05
edge_dim = 64
seed = 0
max_epoch = 500
patience = 100
lr = 0.001
weight_decay = 5e-4
beta = 0.05
residual = True
mini_batch_flag = True
fanout = 5
batch_size = 2048
use_uva = True



[HGAT]
num_layers = 3
hidden_dim = 64
attn_dim = 32
num_classes = 16
negative_slope = 0.2
patience = 100
seed = 0
lr = 0.01
weight_decay = 5e-4
max_epoch = 350



